apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jonny-app

commonLabels:
  app: jonny-app

resources:
  - ./base/deployment.yaml
  - ./base/service.yaml
#  - configMap.yaml