apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app

namePrefix: test-
nameSuffix: -jonny

commonLabels:
  app: app

resources:
  - ./base/deployment.yaml
  - ./base/service.yaml