kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  selector:
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
    - protocol: TCP
      port: 56268
      targetPort: 56268