kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  selector:
  ports:
    - protocol: TCP
      name: api-port
      port: 8001
      targetPort: 8001
    - protocol: TCP
      port: 56268
      name: debug-listen
      targetPort: 56268